/*
 * ICM_42688_P.h
 *
 *  Created on: Dec 10, 2023
 *      Author: Adam
 */

#ifndef ICM_42688_P_H_
#define ICM_42688_P_H_

#include "i2c.h"
#include "stm32l4xx_hal.h"

#include <math.h>


#define ICM_I2C_ADDRESS_I	 (0x69 << 1)

#define ICM_DEVICE_CONFIG      0x11   // R/W - SPI_MODE - SOFT_RESET_CONFIG
#define ICM_DRIVE_CONFIG       0x13   // R/W - I2C_SLEW_RATE SPI_SLEW_RATE
#define ICM_INT_CONFIG         0x14   // - INT2_MODE INT2_DRIVE_CIRCUIT INT2_POLARITY INT1_MODE INT1_DRIVE_CIRCUIT INT1_POLARITY
#define ICM_FIFO_CONFIG        0x16   // R/W FIFO_MODE
#define ICM_TEMP_DATA1         0x1D   // SYNCR TEMP_DATA[15:8]
#define ICM_TEMP_DATA0         0x1E   // SYNCR TEMP_DATA[7:0]
#define ICM_ACCEL_DATA_X1      0x1F   // SYNCR ACCEL_DATA_X[15:8]
#define ICM_ACCEL_DATA_X0      0x20   // SYNCR ACCEL_DATA_X[7:0]
#define ICM_ACCEL_DATA_Y1      0x21   // SYNCR ACCEL_DATA_Y[15:8]
#define ICM_ACCEL_DATA_Y0      0x22   // SYNCR ACCEL_DATA_Y[7:0]
#define ICM_ACCEL_DATA_Z1      0x23   // SYNCR ACCEL_DATA_Z[15:8]
#define ICM_ACCEL_DATA_Z0      0x24   // SYNCR ACCEL_DATA_Z[7:0]
#define ICM_GYRO_DATA_X1       0x25   // SYNCR GYRO_DATA_X[15:8]
#define ICM_GYRO_DATA_X0       0x26   // SYNCR GYRO_DATA_X[7:0]
#define ICM_GYRO_DATA_Y1       0x27   // SYNCR GYRO_DATA_Y[15:8]
#define ICM_GYRO_DATA_Y0       0x28   // SYNCR GYRO_DATA_Y[7:0]
#define ICM_GYRO_DATA_Z1       0x29   // SYNCR GYRO_DATA_Z[15:8]
#define ICM_GYRO_DATA_Z0       0x2A   // SYNCR GYRO_DATA_Z[7:0]
#define ICM_TMST_FSYNCH        0x2B   // SYNCR TMST_FSYNC_DATA[15:8]
#define ICM_TMST_FSYNCL        0x2C   // SYNCR TMST_FSYNC_DATA[7:0]
#define ICM_INT_STATUS         0x2D   // R/C - UI_FSYNC_INT PLL_RDY_INT RESET_DONE_INT DATA_RDY_INT FIFO_THS_INT FIFO_FULL_INT AGC_RDY_INT
#define ICM_FIFO_COUNTH        0x2E   // R FIFO_COUNT[15:8]
#define ICM_FIFO_COUNTL        0x2F   // R FIFO_COUNT[7:0]
#define ICM_FIFO_DATA          0x30   // R FIFO_DATA
#define ICM_APEX_DATA0         0x31   // SYNCR STEP_CNT[7:0]
#define ICM_APEX_DATA1         0x32   // SYNCR STEP_CNT[15:8]
#define ICM_APEX_DATA2         0x33   // R STEP_CADENCE
#define ICM_APEX_DATA3         0x34   // R - DMP_IDLE ACTIVITY_CLASS
#define ICM_APEX_DATA4         0x35   // R - TAP_NUM TAP_AXIS TAP_DIR
#define ICM_APEX_DATA5         0x36   // R - DOUBLE_TAP_TIMING
#define ICM_INT_STATUS2        0x37   // R/C - SMD_INT WOM_Z_INT WOM_Y_INT WOM_X_INT
#define ICM_INT_STATUS3        0x38   // R/C - STEP_DET_INT STEP_CNT_OVF_INT TILT_DET_INT WAKE_INT SLEEP_INT TAP_DET_INT
#define ICM_SIGNAL_PATH_RESET  0x4B   // W/C - DMP_INIT_EN DMP_MEM_RESET_EN ABORT_AND_RESET TMST_STROBE FIFO_FLUSH
#define ICM_INTF_CONFIG0       0x4C   // R/W FIFO_HOLD_LAST_DATA_EN FIFO_COUNT_REC FIFO_COUNT_ENDIAN SENSOR_DATA_ENDIAN UI_SIFS_CFG
#define ICM_INTF_CONFIG1       0x4D   // R/W ACCEL_LP_CLK_SEL RTC_MODE CLKSEL
#define ICM_PWR_MGMT0          0x4E   // R/W TEMP_DIS IDLE GYRO_MODE ACCEL_MODE
#define ICM_GYRO_CONFIG0       0x4F   // R/W GYRO_FS_SEL GYRO_ODR
#define ICM_ACCEL_CONFIG0      0x50   // R/W ACCEL_FS_SEL ACCEL_ODR
#define ICM_GYRO_CONFIG1       0x51   // R/W TEMP_FILT_BW GYRO_UI_FILT_ORD GYRO_DEC2_M2_ORD
#define ICM_GYRO_ACCEL_CONFIG0 0x52   // R/W ACCEL_UI_FILT_BW GYRO_UI_FILT_BW
#define ICM_ACCEL_CONFIG1      0x53   // R/W ACCEL_UI_FILT_ORD ACCEL_DEC2_M2_ORD
#define ICM_TMST_CONFIG        0x54   // R/W - TMST_TO_RESET_EN TMST_RES_EN TMST_DELTA_EN TMST_FSYNC_EN TMST_EN
#define ICM_APEX_CONFIG0       0x56   // R/W DMP_POWER_SAVE TAP_ENABLE PED_ENABLE TILT_ENABLE R2W_EN - DMP_ODR
#define ICM_SMD_CONFIG         0x57   // R/W WOM_INT_MODE WOM_MODE SMD_MODE
#define ICM_FIFO_CONFIG1       0x5F   // R/W FIFO_RESUME_PARTIAL_RD FIFO_WM_GTT_TH FIFO_HIRES_EN FIFO_TMST_FSYNC_EN FIFO_TEMP_EN FIFO_GYRO_EN FIFO_ACCEL_EN
#define ICM_FIFO_CONFIG2       0x60   // R/W FIFO_WM[7:0]
#define ICM_FIFO_CONFIG3       0x61   // R/W FIFO_WM[11:8]
#define ICM_FSYNC_CONFIG       0x62   // R/W FSYNC_UI_SEL FSYNC_UI_FLAG_CLEAR FSYNC_POLARITY
#define ICM_INT_CONFIG0        0x63   // R/W UI_DRDY_INT_CLEAR FIFO_THS_INT_CLEAR FIFO_FULL_INT_CLEAR
#define ICM_INT_CONFIG1        0x64   // R/W INT_TPULSE_DURATION INT_TDEASSERT_DISABLE INT_ASYNC_RESET
#define ICM_INT_SOURCE0        0x65   // R/W UI_FSYNC_INT1_EN PLL_RDY_INT1_EN RESET_DONE_INT1_EN UI_DRDY_INT1_EN FIFO_THS_INT1_EN FIFO_FULL_INT1_EN UI_AGC_RDY_INT1_EN
#define ICM_INT_SOURCE1        0x66   // R/W I3C_PROTOCOL_ERROR_INT1_EN SMD_INT1_EN WOM_Z_INT1_EN WOM_Y_INT1_EN WOM_X_INT1_EN
#define ICM_INT_SOURCE3        0x68   // R/W UI_FSYNC_INT2_EN PLL_RDY_INT2_EN RESET_DONE_INT2_EN UI_DRDY_INT2_EN FIFO_THS_INT2_EN FIFO_FULL_INT2_EN UI_AGC_RDY_INT2_EN
#define ICM_INT_SOURCE4        0x69   // R/W I3C_PROTOCOL_ERROR_INT2_EN SMD_INT2_EN WOM_Z_INT2_EN WOM_Y_INT2_EN WOM_X_INT2_EN
#define ICM_FIFO_LOST_PKT0     0x6C   // R FIFO_LOST_PKT_CNT[15:8]
#define ICM_FIFO_LOST_PKT1     0x6D   // R FIFO_LOST_PKT_CNT[7:0]
#define ICM_SELF_TEST_CONFIG   0x70   // R/W ACCEL_ST_POWER EN_AZ_ST EN_AY_ST EN_AX_ST EN_GZ_ST EN_GY_ST EN_GX_ST
#define ICM_WHO_AM_I           0x75   // R WHOAMI
#define ICM_REG_BANK_SEL       0x76   // R/W BANK_SEL

#define ICM_SENSOR_CONFIG0           0x03   // R/W - ZG_DISABLE YG_DISABLE XG_DISABLE ZA_DISABLE YA_DISABLE XA_DISABLE
#define ICM_GYRO_CONFIG_STATIC2      0x0B   // R/W - GYRO_AAF_DIS GYRO_NF_DIS
#define ICM_GYRO_CONFIG_STATIC3      0x0C   // R/W - GYRO_AAF_DELT
#define ICM_GYRO_CONFIG_STATIC4      0x0D   // R/W GYRO_AAF_DELTSQR[7:0]
#define ICM_GYRO_CONFIG_STATIC5      0x0E   // R/W GYRO_AAF_BITSHIFT GYRO_AAF_DELTSQR[11:8]
#define ICM_GYRO_CONFIG_STATIC6      0x0F   // R/W GYRO_X_NF_COSWZ[7:0]
#define ICM_GYRO_CONFIG_STATIC7      0x10   // R/W GYRO_Y_NF_COSWZ[7:0]
#define ICM_GYRO_CONFIG_STATIC8      0x11   // R/W GYRO_Z_NF_COSWZ[7:0]
#define ICM_GYRO_CONFIG_STATIC9      0x12   // R/W - GYRO_Z_NF_COSWZ_SEL[0] GYRO_Y_NF_COSWZ_SEL[0] GYRO_X_NF_COSWZ_SEL[0] GYRO_Z_NF_COSWZ[8] GYRO_Y_NF_COSWZ[8] GYRO_X_NF_COSWZ[8]
#define ICM_GYRO_CONFIG_STATIC10     0x13   // R/W - GYRO_NF_BW_SEL
#define ICM_XG_ST_DATA               0x5F   // R/W XG_ST_DATA
#define ICM_YG_ST_DATA               0x60   // R/W YG_ST_DATA
#define ICM_ZG_ST_DATA               0x61   // R/W ZG_ST_DATA
#define ICM_TMSTVAL0                 0x62   // R TMST_VALUE[7:0]
#define ICM_TMSTVAL1                 0x63   // R TMST_VALUE[15:8]
#define ICM_TMSTVAL2                 0x64   // R - TMST_VALUE[19:16]
#define ICM_INTF_CONFIG4             0x7A   // R/W - I3C_BUS_MODE - SPI_AP_4WIRE -
#define ICM_INTF_CONFIG5             0x7B   // R/W - PIN9_FUNCTION -
#define ICM_INTF_CONFIG6             0x7C   // R/W ASYNCTIME0_DIS - I3C_EN I3C_IBI_BYTE_EN I3C_IBI_EN I3C_DDR_EN I3C_SDR_EN

#define ICM_CLKDIV              0x2A   // R CLKDIV
#define ICM_APEX_CONFIG1        0x40   // R/W LOW_ENERGY_AMP_TH_SEL DMP_POWER_SAVE_TIME_SEL
#define ICM_APEX_CONFIG2        0x41   // R/W PED_AMP_TH_SEL PED_STEP_CNT_TH_SEL
#define ICM_APEX_CONFIG3        0x42   // R/W PED_STEP_DET_TH_SEL PED_SB_TIMER_TH_SEL PED_HI_EN_TH_SEL
#define ICM_APEX_CONFIG4        0x43   // R/W TILT_WAIT_TIME_SEL SLEEP_TIME_OUT -
#define ICM_APEX_CONFIG5        0x44   // R/W - MOUNTING_MATRIX
#define ICM_APEX_CONFIG6        0x45   // R/W - SLEEP_GESTURE_DELAY
#define ICM_APEX_CONFIG7        0x46   // R/W TAP_MIN_JERK_THR TAP_MAX_PEAK_TOL
#define ICM_APEX_CONFIG8        0x47   // R/W - TAP_TMAX TAP_TAVG TAP_TMIN
#define ICM_APEX_CONFIG9        0x48   // R/W - SENSITIVITY_MODE
#define ICM_ACCEL_WOM_X_THR     0x4A   // R/W WOM_X_TH
#define ICM_ACCEL_WOM_Y_THR     0x4B   // R/W WOM_Y_TH
#define ICM_ACCEL_WOM_Z_THR     0x4C   // R/W WOM_Z_TH
#define ICM_INT_SOURCE6         0x4D   // R/W - STEP_DET_INT1_EN STEP_CNT_OFL_INT1_EN TILT_DET_INT1_EN WAKE_DET_INT1_EN SLEEP_DET_INT1_EN TAP_DET_INT1_EN
#define ICM_INT_SOURCE7         0x4E   // R/W - STEP_DET_INT2_EN STEP_CNT_OFL_INT2_EN TILT_DET_INT2_EN WAKE_DET_INT2_EN SLEEP_DET_INT2_EN TAP_DET_INT2_EN
#define ICM_INT_SOURCE8         0x4F   // R/W - FSYNC_IBI_EN PLL_RDY_IBI_EN UI_DRDY_IBI_EN FIFO_THS_IBI_EN FIFO_FULL_IBI_EN AGC_RDY_IBI_EN
#define ICM_INT_SOURCE9         0x50   // R/W I3C_PROTOCOL_ERROR_IBI_EN - SMD_IBI_EN WOM_Z_IBI_EN WOM_Y_IBI_EN WOM_X_IBI_EN -
#define ICM_INT_SOURCE10        0x51   // R/W - STEP_DET_IBI_EN STEP_CNT_OFL_IBI_EN TILT_DET_IBI_EN WAKE_DET_IBI_EN SLEEP_DET_IBI_EN TAP_DET_IBI_EN
#define ICM_OFFSET_USER0        0x77   // R/W GYRO_X_OFFUSER[7:0]
#define ICM_OFFSET_USER1        0x78   // R/W GYRO_Y_OFFUSER[11:8] GYRO_X_OFFUSER[11:8]
#define ICM_OFFSET_USER2        0x79   // R/W GYRO_Y_OFFUSER[7:0]
#define ICM_OFFSET_USER3        0x7A   // R/W GYRO_Z_OFFUSER[7:0]
#define ICM_OFFSET_USER4        0x7B   // R/W ACCEL_X_OFFUSER[11:8] GYRO_Z_OFFUSER[11:8]
#define ICM_OFFSET_USER5        0x7C   // R/W ACCEL_X_OFFUSER[7:0]
#define ICM_OFFSET_USER6        0x7D   // R/W ACCEL_Y_OFFUSER[7:0]
#define ICM_OFFSET_USER7        0x7E   // R/W ACCEL_Z_OFFUSER[11:8] ACCEL_Y_OFFUSER[11:8]
#define ICM_OFFSET_USER8        0x7F   // R/W ACCEL_Z_OFFUSER[7:0]




// Gyro scale
#define ICM_GYRO_SCALE_2000DPS     0x00
#define ICM_GYRO_SCALE_1000DPS     0x01
#define ICM_GYRO_SCALE_500DPS      0x02
#define ICM_GYRO_SCALE_250DPS      0x03
#define ICM_GYRO_SCALE_125DPS      0x04
#define ICM_GYRO_SCALE_62_5DPS     0x05
#define ICM_GYRO_SCALE_31_25DPS    0x06
#define ICM_GYRO_SCALE_15_625DPS   0x07

// Data rate
#define ICM_GYRO_DATARATE_32kHz    0x01
#define ICM_GYRO_DATARATE_16kHz    0x02
#define ICM_GYRO_DATARATE_8kHz     0x03
#define ICM_GYRO_DATARATE_4kHz     0x04
#define ICM_GYRO_DATARATE_2kHz     0x05
#define ICM_GYRO_DATARATE_1kHz     0x06  // Default
#define ICM_GYRO_DATARATE_200Hz    0x07
#define ICM_GYRO_DATARATE_100Hz    0x08
#define ICM_GYRO_DATARATE_50Hz     0x09
#define ICM_GYRO_DATARATE_25Hz     0x0A
#define ICM_GYRO_DATARATE_12_5Hz   0x0B
#define ICM_GYRO_DATARATE_500Hz    0x0F



// Full scale select for accelerometer
#define ICM_ACCEL_FS_SEL_16G    0x00
#define ICM_ACCEL_FS_SEL_8G     0x01
#define ICM_ACCEL_FS_SEL_4G     0x02
#define ICM_ACCEL_FS_SEL_2G     0x03

// Accelerometer Output Data Rate
#define ICM_ACCEL_ODR_RESERVED  0x00
#define ICM_ACCEL_ODR_32kHz     0x01
#define ICM_ACCEL_ODR_16kHz     0x02
#define ICM_ACCEL_ODR_8kHz      0x03
#define ICM_ACCEL_ODR_4kHz      0x04
#define ICM_ACCEL_ODR_2kHz      0x05
#define ICM_ACCEL_ODR_1kHz      0x06  // Default
#define ICM_ACCEL_ODR_200Hz     0x07
#define ICM_ACCEL_ODR_100Hz     0x08
#define ICM_ACCEL_ODR_50Hz      0x09
#define ICM_ACCEL_ODR_25Hz      0x0A
#define ICM_ACCEL_ODR_12_5Hz    0x0B
#define ICM_ACCEL_ODR_6_25Hz    0x0C
#define ICM_ACCEL_ODR_3_125Hz   0x0D
#define ICM_ACCEL_ODR_1_5625Hz  0x0E
#define ICM_ACCEL_ODR_500Hz     0x0F


typedef struct{

	// handle for i2c
	I2C_HandleTypeDef *i2cHandle;

	// Acceleration and gyroscope data
	float acc_ms2[3];
	float gyr_degs[3];
	float temp_C;

	uint8_t GYROrange;
	uint8_t ACCrange;

	float Gyr_ScaleFactor;
    float Acc_ScaleFactor;

    float Temperature;



	uint8_t address;


}ICM_42688_t;

uint8_t ICM_42688_INIT(ICM_42688_t *dev, I2C_HandleTypeDef *i2cHandle, uint8_t address);
void ICM_42688_SetFullScale_ACC_GYRO_Ranges(ICM_42688_t *dev, uint8_t AccRange,uint8_t AccDataRate, uint8_t GyroRange,uint8_t GyroDataRate);
void ICM_42688_ReadAccGyroTemp(ICM_42688_t *dev);
#endif /* ICM_42688_P_H_ */
